import { Montserrat_Alternates} from "next/font/google";
export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
    
}
const fuente = Montserrat_Alternates({
    weight: ["500"],
    style: ["italic", "normal"],
    subsets: ["latin"]
})

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={fuente.className} >{children}</body>
        </html>
    )
}